language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
    # PyPy versions
  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "pip install ."
  - "pip install nose"
script: nosetests

deploy:
  provider: pypi
  user: python273_travisci
  password:
    secure: n7NMKDxCHymJqVgXgNcdWT2LCHorSGwp6waJG4Xibqc7OEfTUX2S8I5kW45y2QDORTi8GuHKuR6GaPHvMPIt1VspgFQPDzNx4fVCzzq2ej7uyC32qFo2A7e6l2S8CojIXdtm9TffRGxQ5dsY7fNtzU8I0xc821pjufVHpzDP4lyea+udRueZB33xa2KiLFnsDFbsIJzHLQTJUcdgav70uyUFQRf1WLrRILIiX9NzFKHVY5WM3TuME9T2HTR43ZGmv/8xF72ufMb9zMK0gP58L3dcvFFPPn4382obXoQGZkrZj+jWXSjrFeZDM4MKlrYnLuRmwYOpwP3E0O2Zi5XTXRuMDrBB4T4LvvSVjlrDB0p6bOuGiV92yZJoeeIA5tT2aIlq/T2OIW/N/g7OElVImd1iLWawaU1+2AFLPf5vedLfOFUe9dvl1p9hmRS1DZ5eQdYDgg5ZCHbfLgpOqTNmNFDLe2ucdVyxjHYTESo1ttw+l80ulVR8c0OB8aEXomT4bV8lpYtsE10QwNfL6hqwyw2EjNg+hHdCBJYR15ff+op5zsAzPme8+ItV50pQc3gyl4jAmIDEnVhD7FbhpF2iTNPtsOWBsjqJqdigsMbZN0+WoPxBWxZRIpCr3g1qpOm8OS1odKMKT5jHD11RjCfcn57laB0R+1+zhnqPaBFzh3M=
  on:
    tags: true
    branch: master
